#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - develop

jobs:
  include:
    - stage: test
    before_script: - npm install -g @angular/cli
    script: - ng test
    - stage: build
    script: - ng-packagr -p ng-package.json

notifications:
  email:
    on_failure: change
    on_success: change
